server:
  port: 80


spring:
  application:
    name: consul-consumer-order
  cloud:
    consul:
      host: 106.12.129.122
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health


