server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh # 路由的ID，没有固定 规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE # 以微服务名获取地址，lb表示负载均衡协议
          predicates:
            # 多个断言之间是and关系，如同sql查询的多个条件
            - Path=/payment/get/** # 断言,路径相匹配的进行路由
            #- Cookie=username,suchaobin # 带cookie

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka

